name: flutter_temp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  fluttertoast: ^3.1.3
  flutter_tts: 0.8.6
  translator: ^0.1.4
  flutter_spinkit: ^4.1.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_ml_vision:
  image_picker: 0.6.3+1






flutter:


  uses-material-design: true

